"""Original English demo curriculum. LessonView renders these paragraphs as plain text."""


DIRECTIONS = {
    "AI Foundations": "ai-foundations",
    "Knowledge Systems": "knowledge-systems",
    "Automation": "automation",
    "Productivity": "productivity",
    "Private AI": "private-ai",
}


def lesson(title, introduction, explanation, example, task, takeaway):
    return {
        "title": title,
        "text_content": "\n\n".join([
            introduction,
            explanation,
            f"Example\n{example}",
            f"Practical task\n{task}",
            f"Takeaway\n{takeaway}",
        ]),
    }


def module(title, *lessons):
    return {"title": title, "lessons": lessons}


DEMO_COURSES = [
    {
        "title": "AI Fundamentals for Work & Study",
        "slug": "ai-fundamentals-work-study",
        "level": "beginner",
        "direction": "AI Foundations",
        "description": (
            "Explore modern AI and language models through everyday study and work tasks. "
            "This course is for students and professionals who want a practical starting point. "
            "You will learn to frame useful requests, check responses, and build a small workflow "
            "that keeps human judgment in the loop."
        ),
        "modules": [
            module("Understanding Modern AI",
                lesson("What AI can help you do",
                    "AI tools can help classify information, draft text, and suggest patterns. Their value depends on the task and the quality of the material you supply.",
                    "Start with a bounded job whose result you can inspect. Separate generating a first draft from making a final decision; these require different levels of confidence.",
                    "A student asks for five study questions from their own lecture notes, then checks each answer against the notes before revising.",
                    "List three repetitive tasks from your week. Choose one with clear inputs, a small output, and a simple way to check correctness.",
                    "A useful AI task has a purpose, a boundary, and a human check."),
                lesson("Language models and their limits",
                    "A language model generates text from patterns learned during training and the context available in a request. Fluent wording alone does not establish that an answer is true.",
                    "Models can invent references, miss exceptions, or use outdated information. Treat an unsupported claim as something to investigate rather than a source you can cite.",
                    "An assistant proposes a book quotation. You locate the actual passage before using it; if you cannot find it, you omit the quotation.",
                    "Ask for an explanation of a familiar topic. Mark three claims you can verify and note any claim whose supporting evidence is missing.",
                    "Confidence in a sentence should come from evidence, not its style."),
                lesson("Choosing a task and defining success",
                    "A vague goal makes an AI result difficult to judge. Define the audience, expected output, and the conditions that would make the result useful.",
                    "Use a small acceptance checklist before prompting. Include accuracy, completeness, and the format you need, then compare the response against that checklist.",
                    "For a study plan, success means covering four topics in five days, leaving review time, and keeping each session under forty minutes.",
                    "Write a task brief for one study or work activity. Add three observable success criteria and one reason you would reject the result.",
                    "Defining success first makes evaluation faster and more consistent."),
            ),
            module("Working with AI Assistants",
                lesson("Giving an assistant a clear brief",
                    "An assistant needs enough context to understand your request. Explain the situation and identify the exact deliverable instead of relying on a broad instruction.",
                    "Provide only information relevant to the task. A useful brief states what you know, what you need, who will read the result, and any important constraints.",
                    "Draft a welcome email for new workshop participants. Include the supplied date and location, use a friendly tone, and leave unknown details as blanks.",
                    "Turn a one-line request into a brief with context, audience, deliverable, and constraints. Compare the two resulting drafts.",
                    "Specific context helps an assistant produce a draft you can actually use."),
                lesson("Using follow-up questions",
                    "An AI conversation can develop a result in stages. Follow-up questions work best when they refer to a concrete part of the previous response.",
                    "Ask for a correction, comparison, or missing detail rather than simply requesting a better answer. Restate important constraints if the conversation changes direction.",
                    "After receiving a meeting agenda, ask to shorten item three, keep the total duration unchanged, and explain which activity was removed.",
                    "Create a first draft and make two targeted revisions. Record the instruction and the specific improvement from each revision.",
                    "A focused follow-up is easier to evaluate than a complete restart."),
                lesson("Keeping reusable working notes",
                    "Useful AI interactions can become reusable notes. Save the request, essential context, and your review criteria rather than relying on an unstructured chat history.",
                    "Remove private details before sharing a note. Keep a short explanation of when the approach works and what the learner or colleague still needs to check.",
                    "A reusable workshop email note contains placeholders for date and venue, a sample tone, and a checklist for logistical accuracy.",
                    "Save one successful interaction as a short working note with inputs, a prompt, checks, and a description of its intended use.",
                    "Document the method as well as the output so someone else can repeat it."),
            ),
            module("Prompting Fundamentals",
                lesson("Instructions, context, and output format",
                    "A prompt combines a task with the material and rules needed to carry it out. Keeping these parts separate helps you spot missing information.",
                    "Name the action explicitly, supply the relevant context, and describe the desired format. Formatting instructions improve usability, but they do not guarantee factual accuracy.",
                    "From the supplied notes, extract decisions and owners into a two-column table. Use 'not specified' when the notes do not identify an owner.",
                    "Write a prompt with three labeled sections: task, source material, and output requirements. Test whether the response follows each section.",
                    "Structure makes a request easier to understand and review."),
                lesson("Examples and useful constraints",
                    "An example can communicate style or structure more clearly than an adjective. Constraints define what the assistant should preserve, exclude, or leave unresolved.",
                    "Choose an example that represents the real task. Avoid constraints that contradict one another, and distinguish hard requirements from preferences.",
                    "Show a short glossary entry, then ask for three new entries in the same format. Require plain language and prohibit adding facts absent from the supplied notes.",
                    "Create one representative example and two constraints for a recurring task. Explain which parts of the example should be copied and which should vary.",
                    "Good examples demonstrate a pattern without silently introducing new assumptions."),
                lesson("Improving a prompt through comparison",
                    "Prompt improvement is a small experiment. Compare versions on the same task so you can identify which change made a difference.",
                    "Change one important instruction at a time and use the same success checklist. Keep examples of failures; they reveal gaps a polished answer can conceal.",
                    "Compare a general summary request with one that asks for decisions, open questions, and deadlines. Score both against the same meeting notes.",
                    "Write two versions of a prompt, test them on one input, and record one strength and one weakness of each version.",
                    "A prompt is improved by evidence from use, not by added length alone."),
            ),
            module("Responsible and Reliable AI Use",
                lesson("Checking claims and references",
                    "Generated claims need verification when they influence a decision or appear in published work. A plausible reference is not enough; inspect the original source.",
                    "Separate a source's actual statement from the model's interpretation. Record where evidence was found and leave unsupported claims out of the final result.",
                    "A report draft mentions a percentage. You check the underlying table, its year, and the population measured before accepting the number.",
                    "Review a short AI answer and create a claim checklist. Verify two claims using sources you can inspect and label any unresolved claim.",
                    "Verification connects an answer to evidence that another person can review."),
                lesson("Protecting personal and confidential information",
                    "Task context can contain personal or confidential information. Decide what a tool may receive before pasting material into it.",
                    "Follow the rules that apply to your organization and chosen service. Use public or synthetic practice material, remove unnecessary identifiers, and limit access to saved outputs.",
                    "For a scheduling exercise, replace real participant names and email addresses with fictional labels while keeping the timetable structure.",
                    "Take a fictional document and identify fields that would need removal or approval if the document contained real personal information.",
                    "Useful context is the minimum appropriate information needed for the job."),
                lesson("Reviewing bias and communicating AI assistance",
                    "An AI draft may make assumptions about people or circumstances that the source material does not support. Review both its factual claims and its framing.",
                    "Look for stereotypes, omitted perspectives, and unequal treatment of similar cases. Describe AI assistance accurately when your academic or workplace rules require it.",
                    "A student-event announcement assumes every participant can attend in person. You revise it to mention the supplied remote option without inventing accessibility details.",
                    "Review a draft for unsupported assumptions. Rewrite two sentences and add a brief, accurate note explaining how AI contributed to the work.",
                    "Responsible use includes reviewing the way an answer represents people."),
            ),
            module("Practical AI Workflow",
                lesson("Mapping a small human-in-the-loop workflow",
                    "A workflow connects several actions toward a repeatable result. Begin with a simple sequence that makes the input, AI step, and human review visible.",
                    "Identify who supplies the material, who checks the output, and what happens when a check fails. Keeping responsibility explicit prevents a draft from being mistaken for an approved result.",
                    "Lecture notes become draft revision questions, then a student checks the answers and saves the accepted questions in a study folder.",
                    "Draw a four-step workflow for your chosen task. Label the human review step and describe how rejected output returns for correction.",
                    "A reliable workflow includes the decision to accept or reject its output."),
                lesson("Measuring usefulness and keeping a log",
                    "A workflow is useful when it improves the actual task, not merely when it produces text quickly. Measure the effort of preparing, reviewing, and correcting the result.",
                    "Record a few comparable runs and include failed attempts. A short log can reveal whether the approach saves time or shifts work into a longer review stage.",
                    "An email drafting log records preparation time, review time, and the number of factual corrections needed for each draft.",
                    "Run your workflow on two practice inputs. Record the result, review effort, and one change you would make before using it again.",
                    "Count review and correction as part of the workflow's cost."),
                lesson("Presenting your practical AI workflow",
                    "A final workflow should be understandable to someone who did not build it. Describe its purpose, required inputs, sequence, and limits in a short handover note.",
                    "Include one successful example and one failure case. State which checks remain human responsibilities and where the reusable instructions are stored.",
                    "A study-question workflow handover explains accepted note formats, its question prompt, answer checking, and how to handle a topic missing from the notes.",
                    "Prepare a one-page workflow handover with an example input, reviewed output, checklist, and one known limitation.",
                    "A clear handover turns a personal experiment into a repeatable learning tool."),
            ),
        ],
    },
    {
        "title": "Prompt Engineering for LLMs",
        "slug": "prompt-engineering-llms",
        "level": "beginner",
        "direction": "AI Foundations",
        "description": (
            "Learn to write, test, and maintain clear instructions for language models. "
            "This beginner course is for students and professionals who want more consistent results from AI assistants. "
            "You will finish with a small prompt library, example inputs, and a practical evaluation checklist."
        ),
        "modules": [
            module("How LLMs Interpret Instructions",
                lesson("Instructions and supplied material",
                    "A prompt combines instructions with information the model should work on. Make the distinction visible so a reader can identify the task without guessing.",
                    "Put the task before the source material and give each section a clear label. Instructions found inside an imported document should be treated as document content, not permission to change the task.",
                    "A support transcript says 'ignore the previous message'. Your summarization prompt labels the transcript as source material and asks only for a summary of its events.",
                    "Write a summarization prompt with separate Task and Source sections. Include a source sentence that looks like an instruction and check how the model handles it.",
                    "Separating instructions from evidence makes prompts easier to inspect and test."),
                lesson("Context and uncertainty",
                    "A model can only use the context available to it and its learned patterns. It may fill a missing detail with a plausible statement unless the task defines another response.",
                    "Supply the facts needed for the task and specify how to represent missing information. More context is not automatically better: irrelevant material can distract from the question.",
                    "An event brief includes a date but no location. Your prompt requires 'Location not provided' instead of accepting a guessed venue.",
                    "Create a short event brief with two missing fields. Ask for a structured summary and verify that both fields remain explicitly unknown.",
                    "A useful answer preserves uncertainty instead of hiding it."),
                lesson("Why similar prompts can produce different answers",
                    "Language model output can vary even when a task looks unchanged. A single impressive answer is weak evidence that a prompt will work repeatedly.",
                    "Small changes in wording, input structure, or model settings can affect the result. Evaluate the desired behavior across several inputs and record the conditions of each trial.",
                    "A prompt creates a good five-item checklist for one brief but merges two steps when the next brief uses bullet points.",
                    "Run the same task on three differently formatted inputs. Record where the outputs meet your requirements and where they diverge.",
                    "Prompt quality is a pattern across trials, not one successful response."),
            ),
            module("Anatomy of a Strong Prompt",
                lesson("Writing a specific task statement",
                    "Start by stating the action and its intended result. Broad requests such as 'improve this' leave the model to choose both the problem and the success criteria.",
                    "Describe what should change and which facts must remain intact. A role can provide useful perspective, but it does not replace explicit task instructions.",
                    "Instead of 'act as an editor', ask for a shorter announcement for first-year students that preserves the supplied dates and registration link.",
                    "Rewrite a vague request as one action, one audience, and three concrete requirements. Check whether another person could evaluate the result.",
                    "Specific actions make the result easier to judge."),
                lesson("Adding the right context",
                    "Context explains the situation in which an answer will be used. Include the audience, purpose, and relevant source facts without burying the task in unrelated history.",
                    "Separate required facts from optional background. If a fact must appear exactly, say so and provide its approved wording rather than expecting the model to infer it.",
                    "A workshop invitation supplies the audience, confirmed schedule, and a registration deadline, while leaving out unrelated notes from the planning meeting.",
                    "Prepare a compact context block for an invitation. Mark two facts as required and remove one detail that does not help the reader decide whether to attend.",
                    "Good context reduces ambiguity while keeping the task visible."),
                lesson("Defining the output contract",
                    "The output contract describes the shape and boundaries of a response. It can specify headings, fields, length, and how empty values should be represented.",
                    "Choose a format that suits the next step. A human reviewer may prefer short paragraphs, while a program needs consistently named fields and validation before use.",
                    "A meeting recap must contain Decisions, Owners, and Open questions. An owner absent from the notes is written as 'Not assigned'.",
                    "Design an output contract for a meeting recap. Test it with notes that contain no decisions and specify what that section should show.",
                    "A predictable structure helps both review and reuse."),
            ),
            module("Context, Examples and Constraints",
                lesson("Showing examples without overfitting",
                    "Examples demonstrate the relationship between an input and a desired output. They are most useful when they explain a pattern rather than merely supply an answer to copy.",
                    "Use examples that vary in meaningful ways, including an edge case. Avoid examples with accidental details that could be mistaken for required content.",
                    "Two ticket-labeling examples show an urgent service failure and a routine question. A third shows that insufficient information should produce 'Needs review'.",
                    "Write three input-output examples for a simple labeling task. Explain which feature determines each label and which details are incidental.",
                    "Representative examples teach the decision rule more clearly."),
                lesson("Constraints and conflicting requirements",
                    "Constraints define limits such as length, tone, or prohibited assumptions. Too many competing requirements can make a prompt hard to satisfy or evaluate.",
                    "Rank essential requirements and clarify what to do when they conflict. Never request a complete factual explanation and an unrealistically small word limit without deciding which matters more.",
                    "A summary should stay under 100 words, but all confirmed deadlines must appear. The prompt permits a slightly longer answer when needed to preserve those deadlines.",
                    "Review a prompt with five constraints. Identify one conflict and rewrite it with an explicit priority or fallback.",
                    "Clear priorities are more useful than a long list of incompatible rules."),
                lesson("Preparing long source material",
                    "Long inputs are easier to work with when their sections and purpose are clear. Preserve structure so important facts can be traced back to the original material.",
                    "Split material at meaningful boundaries and retain source labels. Summarizing every chunk can lose details, so check the final result against the original sections relevant to the question.",
                    "A project report is divided into Scope, Findings, and Limitations. Each extracted point carries its section label into the final summary.",
                    "Divide a practice document into labeled sections. Ask a focused question and confirm that each answer points to a relevant source section.",
                    "Structure helps preserve evidence when working with larger inputs."),
            ),
            module("Iteration and Evaluation",
                lesson("Creating a small test set",
                    "A test set is a collection of inputs that reveals how a prompt behaves. Include ordinary cases, missing information, and a case that should be rejected or sent for review.",
                    "Write expected behavior before inspecting model output. Otherwise, it is easy to redefine success around whichever answer the model happens to provide.",
                    "An action-item extractor is tested on clear assignments, ambiguous owners, no tasks, and quoted text containing unrelated instructions.",
                    "Create four test inputs for your prompt and write one acceptance rule for each. Keep these examples separate from the examples inside the prompt.",
                    "A fixed test set makes prompt revisions comparable."),
                lesson("Comparing one change at a time",
                    "Iteration should help you learn why a result changed. Revising the task, examples, and output format together makes that explanation difficult.",
                    "Change one major element, rerun the same test set, and record the outcome. Keep a previous version available when a revision improves one case but breaks another.",
                    "You add a missing-value rule to an extractor without changing its labels. The same tests show fewer invented dates and unchanged extraction of known dates.",
                    "Compare two prompt versions that differ in one rule. Record which tests improve, regress, or remain unchanged.",
                    "Controlled revisions turn trial and error into useful evidence."),
                lesson("Scoring accuracy and usability",
                    "A response can be fluent yet unusable for the task. Evaluate correctness, completeness, source support, and whether the output fits its intended workflow.",
                    "Use a short rubric with observable checks. Treat serious factual errors separately from minor style preferences so polished wording does not hide an unsafe result.",
                    "A recap receives separate checks for correct deadlines, named owners supported by the notes, and the required three-section format.",
                    "Write a five-item rubric and score two outputs. For every failed check, identify the exact sentence or missing field that caused it.",
                    "Evaluation becomes repeatable when scores point to specific evidence."),
            ),
            module("Building a Prompt Library",
                lesson("Turning a prompt into a template",
                    "A reusable prompt separates stable instructions from values that change for each task. Clearly named placeholders make the expected inputs easier to supply.",
                    "Document required fields and the allowed format of each one. Leave no placeholder silently unresolved, and avoid embedding private sample data in a shared template.",
                    "An announcement template uses AUDIENCE, CONFIRMED_FACTS, and MAX_LENGTH instead of a previous event's real names and contact details.",
                    "Convert a tested prompt into a template with three placeholders. Fill it with a new fictional example and check for leftover sample values.",
                    "A template should make its input requirements obvious."),
                lesson("Documenting versions and limitations",
                    "A prompt library needs enough context for someone else to use it responsibly. Store the purpose, input requirements, tested cases, and known limitations beside each template.",
                    "Give revisions a simple version label and record what changed. Include the model and settings used during evaluation because results may change in another environment.",
                    "A recap template note says version 2 improved missing-owner handling and has only been tested on short English meeting notes.",
                    "Write a library entry for your template with its version, test conditions, two examples, and one limitation.",
                    "Documentation explains where a prompt has earned confidence."),
                lesson("Delivering your starter prompt library",
                    "A starter library should solve a few clearly defined tasks well. A small collection with tests is easier to maintain than many unverified prompts.",
                    "Choose complementary tasks, use a consistent entry format, and include review instructions. Ask another person to try a template using only its documentation.",
                    "A study library contains a question generator, a source-grounded summary prompt, and an explanation checker, each with sample inputs and acceptance criteria.",
                    "Package three templates with documentation and test results. Record one improvement suggested by a person trying them for the first time.",
                    "A useful library combines prompts with instructions for checking their results."),
            ),
        ],
    },
    {
        "title": "AI Research & Knowledge Systems",
        "slug": "ai-research-knowledge-systems",
        "level": "intermediate",
        "direction": "Knowledge Systems",
        "description": (
            "Explore how AI can support research without losing the connection between claims and sources. "
            "The course is for learners who already use AI assistants and want to organize research for personal or team projects. "
            "You will build a small knowledge workspace with source records, evidence notes, and a reviewable research brief."
        ),
        "modules": [
            module("From Information to Knowledge",
                lesson("Defining a research question",
                    "A research question gives direction to the material you collect. It should be narrow enough to answer and connected to a decision or learning goal.",
                    "Describe the scope, intended audience, and what evidence would help. AI can suggest refinements, but you should choose the question and confirm that it is practical to investigate.",
                    "Instead of researching 'remote work', a team asks which onboarding difficulties new remote colleagues report during their first month.",
                    "Write a broad topic, then narrow it to one question with a population, context, and time boundary. List two kinds of evidence you would seek.",
                    "A precise question makes collecting and rejecting information easier."),
                lesson("Distinguishing facts, interpretations, and gaps",
                    "Research notes often mix reported facts with a reader's interpretation. Keeping them separate prevents a tentative idea from becoming an unsupported conclusion.",
                    "Label direct observations, interpretations, and unanswered questions. An AI summary is another interpretation until you verify its claims against the underlying source.",
                    "A survey reports that eight of twelve participants struggled to find documents. 'The team needs a new tool' is an interpretation, not a survey finding.",
                    "Read a short fictional report and label three facts, two interpretations, and one information gap.",
                    "Useful knowledge retains the boundary between evidence and judgment."),
                lesson("Designing a source record",
                    "A source record stores enough information to find and assess a document later. A saved link alone rarely explains why a source was useful.",
                    "Record its title, author or organization, date, location, and relevance to your question. Add the access date when the content is likely to change.",
                    "A source record for a team survey includes its collection period, sample size, file location, and the research question it informs.",
                    "Create a source-record template and fill it for two practice documents. Include one limitation for each source.",
                    "Source records make a research workspace easier to audit and maintain."),
            ),
            module("AI-Assisted Research",
                lesson("Planning a research search",
                    "Use an AI assistant to suggest search terms and possible angles before collecting evidence. Suggestions are a starting plan rather than proof that useful sources exist.",
                    "Combine synonyms, narrower terms, and opposing viewpoints. Search actual repositories or websites and record which queries lead to relevant material.",
                    "For an onboarding question, search terms include document discovery, first-month support, and remote employee orientation rather than only 'remote work'.",
                    "Generate six search queries, select three, and explain which aspect of your question each query targets.",
                    "A research plan helps search deliberately instead of collecting whatever appears first."),
                lesson("Summarizing a supplied source",
                    "A source-grounded summary should reflect the supplied document, including its limits. It should not blend in outside facts unless the task explicitly asks for separate background.",
                    "Request findings, method, and limitations with page or section references where available. Check each point against the source, especially numbers and claims of causation.",
                    "A survey summary preserves the small sample size and describes a reported association without presenting it as a proven cause.",
                    "Summarize a short practice source using three headings: Findings, Method, and Limits. Verify one sentence under each heading.",
                    "A useful summary keeps the source's uncertainty visible."),
                lesson("Comparing several sources",
                    "Comparison reveals agreement, disagreement, and differences in scope. Sources can appear to conflict because they study different groups or use different definitions.",
                    "Create a comparison table with one row per source and consistent questions across columns. Trace every entry back to a document before drawing a shared conclusion.",
                    "Two onboarding studies differ in company size and survey period. Their results are compared with those differences visible beside the findings.",
                    "Compare two fictional sources by question, population, method, finding, and limitation. Write one cautious conclusion supported by both.",
                    "Comparison needs context as well as matching statements."),
            ),
            module("Working with Sources",
                lesson("Checking credibility and relevance",
                    "A source can be authentic and still be unsuitable for your question. Assess its origin, evidence, incentives, and relationship to the claim you need to evaluate.",
                    "Prefer direct evidence when available and distinguish it from commentary. Check dates and methodology rather than relying only on a professional-looking page or confident language.",
                    "A vendor article describes customer benefits but does not explain its sample. You retain it as a perspective and seek independent evidence for numerical claims.",
                    "Assess two practice sources using origin, evidence, date, and relevance. State what each source can and cannot support.",
                    "Credibility is a reasoned assessment tied to a specific claim."),
                lesson("Keeping citations connected to claims",
                    "A citation is useful when a reader can locate evidence for the associated statement. A valid link does not guarantee that the linked document supports the claim.",
                    "Store claim notes with a source identifier and location. Verify any citation suggested by AI by opening the source and checking the actual passage.",
                    "A note about response time points to table 2 in a report, while a separate note about satisfaction points to its survey section.",
                    "Create three claim notes with source locations. For each, explain in your own words how the cited evidence supports the claim.",
                    "Traceable claims are easier to review than a detached bibliography."),
                lesson("Handling disagreement and missing evidence",
                    "Conflicting evidence is a research result worth preserving. Do not ask an assistant to force agreement merely to make the final brief sound decisive.",
                    "Record the disagreement, plausible reasons, and what additional evidence would help. Distinguish a source that contradicts a claim from a source that simply does not address it.",
                    "One report finds faster onboarding and another reports no change. Differences in training support become a question for further investigation.",
                    "Write a disagreement note for two fictional findings. Include one next research step without choosing a winner prematurely.",
                    "A knowledge system should preserve unresolved questions alongside conclusions."),
            ),
            module("Building a Knowledge Base",
                lesson("Choosing a simple information structure",
                    "A knowledge base is a system for finding and reusing verified material. Start with a small structure that matches how you expect to ask questions later.",
                    "Separate source records, evidence notes, and summaries. Give each item a stable identifier so links survive changes to its display title.",
                    "A research folder contains S01-source records, N01-evidence notes, and a topic overview linking to the relevant notes.",
                    "Design a three-part folder or table structure for your question. Describe where an original document, a claim note, and a synthesis would live.",
                    "A modest, consistent structure is easier to use than a complicated taxonomy."),
                lesson("Adding tags and useful connections",
                    "Tags describe shared themes, while links express a specific relationship between notes. Use both sparingly so they support navigation instead of adding maintenance work.",
                    "Choose a small tag vocabulary and define ambiguous terms. Link a conclusion to its evidence and a question to the notes that explain why it remains open.",
                    "An onboarding note carries the tag document-discovery and links to the survey finding that motivated a proposed index page.",
                    "Tag six practice notes with no more than four tags. Add two links and explain the relationship represented by each.",
                    "Connections are useful when their meaning is clear to another reader."),
                lesson("Maintaining a current knowledge base",
                    "Knowledge becomes less reliable when old material looks current. Store review dates and identify which notes depend on changing facts or policies.",
                    "Assign ownership where several people contribute. Archive superseded summaries with a reason rather than silently replacing evidence that readers may still reference.",
                    "A team policy note records its effective date and owner. A monthly review checks whether its source has been replaced.",
                    "Create a maintenance checklist for your workspace, including one review trigger and a way to mark outdated material.",
                    "Maintenance is part of making knowledge dependable."),
            ),
            module("Final Research Workspace",
                lesson("Assembling a small evidence collection",
                    "The final workspace should demonstrate a complete path from question to evidence. Choose a manageable collection that you can inspect rather than maximizing the number of links.",
                    "Use several relevant sources, complete their records, and write claim notes in your own words. Include at least one limitation or unresolved issue.",
                    "A workspace on meeting effectiveness contains three source records, six evidence notes, and one disagreement note.",
                    "Assemble a small practice workspace with three sources and six linked notes. Review it for missing source identifiers.",
                    "A small, traceable collection can support a useful research result."),
                lesson("Writing an evidence-based brief",
                    "A research brief explains what the evidence supports and what remains uncertain. Its structure should help the intended reader make a decision or choose a next step.",
                    "State the question, key findings, limitations, and recommended follow-up. Keep recommendations distinct from findings and attach relevant source references to factual claims.",
                    "A brief recommends testing an onboarding index, while explaining that current evidence comes from a small internal survey.",
                    "Write a one-page brief from your workspace. Check that every major factual statement has a source and every recommendation is labeled as judgment.",
                    "A clear brief connects evidence to action without overstating certainty."),
                lesson("Reviewing and handing over the workspace",
                    "A workspace is ready to share when another person can navigate it and verify its conclusions. A handover should explain the structure and the remaining work.",
                    "Ask a reviewer to follow two claims back to their sources. Record broken links, unclear labels, and questions that your documentation did not answer.",
                    "A reviewer finds the survey behind a conclusion but cannot interpret the tag 'support'. The handover adds a tag definition and clarifies the note.",
                    "Prepare a short workspace guide, conduct a two-claim traceability check, and record one improvement plus one unresolved research question.",
                    "Reviewable knowledge is more valuable than a collection only its creator understands."),
            ),
        ],
    },
    {
        "title": "AI Automation with n8n",
        "slug": "ai-automation-n8n",
        "level": "intermediate",
        "direction": "Automation",
        "description": (
            "Learn to design small automations that connect data, applications, and language models using n8n. "
            "This course suits learners comfortable with AI assistants who want to understand repeatable workflows. "
            "You will plan and test an automation with explicit inputs, validation, error handling, and a human approval step."
        ),
        "modules": [
            module("Automation Fundamentals",
                lesson("Why automate repetitive work?",
                    "Automation is useful when a recurring task has understandable inputs and a consistent process. Begin with work whose successful result you can describe and check.",
                    "Estimate frequency, manual effort, and the cost of a mistake. A task that requires changing judgment at every step may first need a clearer process rather than an automation.",
                    "A team repeatedly copies approved request details into a tracker. Its stable fields make a safer first project than automatically deciding which requests deserve approval.",
                    "List three repetitive tasks. Choose one using frequency, clear inputs, and ease of checking, then define its success criteria.",
                    "A good automation candidate has a repeatable process and a measurable result."),
                lesson("Mapping a workflow",
                    "A workflow map describes the route from an incoming event to a useful result. Include decision points and exceptions before choosing particular tools.",
                    "Label the data needed at each step and who is responsible for approval. Separate preparing a draft from publishing or sending it so review remains possible.",
                    "A request arrives, required fields are checked, a draft response is prepared, and a person approves it before any message is sent.",
                    "Draw a five-step workflow for a fictional request. Add a branch for a missing field and mark where the workflow must stop for review.",
                    "Mapping the process exposes assumptions before they become automated actions."),
                lesson("Triggers, actions, and data flow",
                    "A trigger starts a workflow, while later actions transform data or interact with another system. Data flow determines which values are available to each action.",
                    "Define a small input contract and a matching output contract. Test missing values and unexpected formats before connecting a real destination.",
                    "A practice workflow starts with a manually supplied request containing request_id and topic, then creates a normalized record for later steps.",
                    "Write an input and output example for your workflow. Identify one field that must be preserved unchanged from start to finish.",
                    "Clear data contracts keep connected steps understandable."),
            ),
            module("Working with n8n",
                lesson("Building a small node sequence",
                    "In n8n, a workflow connects nodes that perform steps on data. Start with a manual trigger and a few transformations so you can inspect the process safely.",
                    "Give nodes names that explain their purpose. Observe the output after each step and compare it with the workflow map before adding external services.",
                    "A practice sequence begins manually, loads a fictional request, and prepares the fields needed for a draft summary.",
                    "Sketch or build a three-node practice workflow using fictional data. Record the expected output at each node and explain its responsibility.",
                    "Small, observable steps are easier to debug than a large opaque workflow."),
                lesson("Mapping fields with expressions",
                    "Expressions let a node use values from workflow data rather than fixed text. Field mapping translates an incoming record into the structure the next step expects.",
                    "Check where each value originates and how empty values are handled. Avoid relying on a field name that only appears in one successful sample.",
                    "An incoming topic becomes the subject field of a draft record. A missing topic is routed for review instead of being replaced with an invented subject.",
                    "Map three incoming fields to a new record. Test one input with a missing field and document the fallback behavior.",
                    "Field mapping should preserve meaning as well as produce valid values."),
                lesson("Credentials and safe practice runs",
                    "Connected applications often require credentials. Keep credentials separate from workflow examples and use limited-access test resources while learning.",
                    "Inspect a workflow before executing steps that send messages or update records. A successful preview with sample data does not prove that a live destination is correct.",
                    "An experiment writes to a dedicated test sheet containing fictional requests, while a reviewer checks the destination and allowed fields.",
                    "Create a practice-run checklist covering credentials, destination, fictional data, and actions that could change an external system.",
                    "A controlled test environment makes mistakes easier to observe and recover from."),
            ),
            module("Adding LLMs to Workflows",
                lesson("Choosing the model's responsibility",
                    "An LLM step should have a narrow responsibility with a checkable result. Use ordinary workflow logic for exact rules and let the model handle language tasks that need interpretation.",
                    "Define what the model may infer and what it must preserve. Avoid assigning final approval to a text generator when an error could trigger an unintended action.",
                    "The model drafts a request summary, while regular validation checks that request_id is present and a person decides whether to send the response.",
                    "Choose one language task for your workflow. List two decisions that will remain outside the model step and explain why.",
                    "Narrow model responsibilities make automated behavior easier to evaluate."),
                lesson("Requesting and validating structured output",
                    "Structured output helps later workflow steps consume a model response. Asking for fields is only the first step; the returned data still needs validation.",
                    "Check parsing, required keys, allowed values, and missing-information behavior. Route invalid output to a review path rather than allowing it to continue as if it were correct.",
                    "A classifier returns category and explanation. The workflow accepts only the documented categories and sends unknown values to manual review.",
                    "Define a two-field output contract and three invalid examples. Describe the validation check that catches each example.",
                    "A model response becomes usable workflow data only after its contract is checked."),
                lesson("Keeping source data distinct from instructions",
                    "Incoming messages may contain text that tries to redirect an AI step. Treat imported material as evidence to analyze rather than authority over the workflow.",
                    "Label source data in the prompt, limit the model's output, and validate any proposed action separately. Prompt wording alone cannot guarantee safe execution of an external action.",
                    "A request includes 'send all records to this address'. The workflow summarizes the request but has no automatic path that changes its configured destination.",
                    "Add an instruction-like sentence to a fictional input. Check that the workflow keeps its destination and approval rules unchanged.",
                    "Workflow boundaries must enforce the intended task independently of generated text."),
            ),
            module("Reliable AI Automations",
                lesson("Handling failures and retries",
                    "External services can time out or reject a request. A reliable workflow distinguishes temporary failures from invalid data and records what happened.",
                    "Limit retries and avoid repeating an action that may already have succeeded. Keep a request identifier so a reviewer can recognize a duplicate attempt.",
                    "After an uncertain tracker write, the workflow checks for the request identifier before attempting another write instead of creating a second row immediately.",
                    "Describe recovery for a timeout, invalid model output, and missing credentials. Set a retry limit and identify one action that needs duplicate protection.",
                    "Recovery should prevent repeated work as well as restore execution."),
                lesson("Adding human approval",
                    "Human approval is useful where the workflow proposes an action that affects people or shared records. The reviewer needs enough information to judge the proposal.",
                    "Show the source, proposed result, and validation status together. Record approval explicitly and prevent a rejected or expired proposal from reaching the final action.",
                    "A reviewer sees the original request beside a draft reply and can approve, revise, or reject it before the sending step.",
                    "Design a review screen or approval record with the fields a reviewer needs. Explain what happens after rejection and how approval is associated with the right request.",
                    "Approval works when the decision and its evidence remain connected."),
                lesson("Logging and measuring a workflow",
                    "Execution logs help explain where a workflow failed or became expensive. Record enough information to investigate without copying sensitive source material into every log entry.",
                    "Track request identifiers, step status, duration, and review outcome. Compare the complete workflow effort with the manual process, including corrections and failed runs.",
                    "A weekly report counts completed drafts, validation failures, and human corrections using identifiers rather than storing full private messages.",
                    "Design a five-field execution log and a small success metric. State which information should be excluded from the log.",
                    "Useful monitoring reveals both benefits and recurring failure patterns."),
            ),
            module("Final Automation Project",
                lesson("Preparing the project specification",
                    "A project specification turns a workflow idea into a testable agreement. State the input, desired result, allowed actions, and conditions that require review.",
                    "Keep the first version small and use fictional data. Include explicit acceptance criteria so a finished-looking canvas does not substitute for working behavior.",
                    "A request-triage project accepts three fields, proposes a category and summary, and produces an approved draft record without sending messages automatically.",
                    "Write a one-page specification for your automation, including three acceptance checks and one excluded action.",
                    "A bounded specification keeps the final project practical to test."),
                lesson("Testing normal and exceptional inputs",
                    "Final testing should cover the workflow's entire path, including branches that do not produce a successful result. Failures are useful evidence of whether safeguards work.",
                    "Use ordinary, missing-field, duplicate, and instruction-like inputs. Verify that invalid cases stop or reach review and that valid cases preserve their identifiers.",
                    "A duplicate request reaches a review branch, while a new complete request produces one draft and one associated execution record.",
                    "Run or simulate four test cases and record their expected and observed routes. Fix one mismatch before declaring the project ready.",
                    "An automation is tested by its exception handling as well as its successful path."),
                lesson("Documenting operation and recovery",
                    "A finished workflow needs an operating guide for someone returning after a break. Explain how to run a test, inspect results, stop actions, and recover from a failed step.",
                    "List required connections without exposing credentials. Include known limitations and who should review errors before the workflow resumes.",
                    "A handover note identifies the test destination, approval owner, duplicate check, and steps for inspecting a failed request by its identifier.",
                    "Prepare a short operating guide with a workflow map, test case, recovery procedure, and one known limitation.",
                    "An understandable recovery procedure is part of delivering an automation."),
            ),
        ],
    },
    {
        "title": "AI for Documents & Office Work",
        "slug": "ai-documents-office-work",
        "level": "intermediate",
        "direction": "Productivity",
        "description": (
            "Practice using language models to summarize, extract information from, and draft everyday office documents. "
            "The course is for learners who already use AI assistants and want a more dependable document process. "
            "You will create a reviewable workflow that preserves source facts, marks missing information, and produces a clear final handover."
        ),
        "modules": [
            module("AI and Document Workflows",
                lesson("Choosing a document task",
                    "Document work includes reading, extracting, drafting, and reviewing. Choose one of these tasks before asking an assistant to work on a file.",
                    "Define the reader and the result they need. Distinguish a summary for quick orientation from an extraction that must preserve every required field.",
                    "A manager needs a brief account of meeting decisions, while a coordinator needs a complete list of assigned tasks and deadlines from the same notes.",
                    "Choose a fictional office document and describe two possible tasks. Select one and write three requirements for its output.",
                    "A clear document task determines what must be retained and checked."),
                lesson("Preparing source material",
                    "Documents may contain headings, tables, scanned text, or comments that affect interpretation. Check what the assistant actually receives before trusting its output.",
                    "Preserve section labels and inspect converted text for missing rows or misread characters. Use approved, non-sensitive practice material while developing the workflow.",
                    "A copied table loses its column boundaries, making an amount look like a date. You correct the plain-text structure before extraction.",
                    "Inspect a short converted document and identify two possible formatting errors. Prepare a clean source version with clear section labels.",
                    "Source preparation prevents avoidable errors from reaching later steps."),
                lesson("Planning review and document versions",
                    "A document workflow needs a way to distinguish a source, an AI draft, and an approved version. Clear version labels reduce accidental use of unfinished work.",
                    "Record the source version used for each draft and define who reviews it. A new source should trigger a new review rather than silently updating a previously approved result.",
                    "A meeting recap records that it was drafted from notes version 2 and approved after a reviewer checked its dates and owners.",
                    "Design a simple naming and review process for source, draft, and approved files. Describe what happens when the source changes.",
                    "Version clarity keeps approval attached to the document that was actually reviewed."),
            ),
            module("Summarization and Extraction",
                lesson("Summarizing for a particular reader",
                    "A useful summary selects information according to the reader's purpose. It should preserve key facts and limitations rather than simply shorten every paragraph equally.",
                    "Specify focus areas, length, and which details must remain exact. Compare the summary with the source to check for omitted exceptions or stronger claims than the document supports.",
                    "An executive summary highlights decisions and unresolved risks, while retaining the source's provisional timeline instead of presenting it as confirmed.",
                    "Write a summary prompt for one reader and compare its result with the source. Identify one fact to retain and one detail that can be omitted.",
                    "A summary is useful when it supports the reader's task without changing the evidence."),
                lesson("Extracting fields and missing values",
                    "Extraction turns a document into a set of named fields. Decide what counts as evidence for each field and how to mark information that is not present.",
                    "Keep dates, amounts, and names tied to source locations. Validate the extracted values and do not infer an owner merely because a person is mentioned nearby.",
                    "An action record contains task, owner, and due_date. Notes without a deadline produce an empty due_date with a 'Not specified' status.",
                    "Define four extraction fields and process a fictional memo with one missing value. Check each populated field against the source.",
                    "Reliable extraction includes an honest representation of missing information."),
                lesson("Comparing document versions",
                    "Version comparison asks what changed and why those changes matter. A generated comparison should be checked against both documents before it guides decisions.",
                    "Separate additions, removals, and changed values. Give each difference a section reference and distinguish wording edits from changes to obligations or dates.",
                    "A project brief changes a delivery date and simplifies its introduction. The comparison marks the date as an operational change and the introduction as a wording change.",
                    "Compare two short fictional briefs and create a three-row change log. Verify every row in both versions.",
                    "A good comparison explains specific changes instead of describing overall similarity."),
            ),
            module("Drafting and Rewriting",
                lesson("Drafting from an approved brief",
                    "An approved brief gives a drafting assistant a factual boundary. It should contain the message's purpose, audience, required facts, and any unanswered questions.",
                    "Ask for a draft rather than an automatically ready message. Check that the text adds no commitments, benefits, or details that the brief does not support.",
                    "A training announcement mentions the confirmed time and topic but does not promise certificates or refreshments because neither appears in the brief.",
                    "Create a fictional brief and draft a short announcement. Mark each factual statement and confirm that it appears in the brief.",
                    "A factual brief helps keep a fluent draft within authorized information."),
                lesson("Rewriting while preserving meaning",
                    "Rewriting can improve clarity, tone, or length without changing the underlying message. State which elements must remain exact and which may be rephrased.",
                    "Compare the rewritten text with the original for dates, quantities, conditions, and responsibility. Friendly language should not weaken a required action or create a new promise.",
                    "A concise reminder preserves a mandatory submission deadline while replacing a long introductory paragraph with one clear sentence.",
                    "Rewrite a fictional reminder for a different audience. Check four factual elements and explain one wording change that improves clarity.",
                    "A successful rewrite improves expression while preserving the document's commitments."),
                lesson("Reviewing tone and accessibility",
                    "Office documents should be understandable to the people expected to act on them. Review tone, sentence structure, and unexplained terms with that audience in mind.",
                    "Ask an assistant to suggest clearer wording, then judge each suggestion yourself. Keep necessary technical terms and explain them instead of replacing them with vague language.",
                    "A process note explains 'request owner' on first use and puts the required action before background information.",
                    "Review a short draft for jargon and unclear actions. Revise two sentences and check that the responsible person and next step remain explicit.",
                    "Clarity means readers can understand both the message and what to do next."),
            ),
            module("Structured Office Workflows",
                lesson("Creating reusable document templates",
                    "Templates make recurring documents easier to prepare and review. Separate fixed structure from fields that need fresh facts each time.",
                    "Label required fields and provide a missing-information rule. Use fictional examples so a copied template does not carry a real person's details into a new document.",
                    "A status-update template includes completed work, next steps, risks, and decisions needed, with a note to write 'None reported' only when that has been confirmed.",
                    "Build a four-section template and complete it for a fictional project. Check for unresolved placeholders and unsupported default statements.",
                    "A template should encourage fresh verification rather than automatic copying."),
                lesson("From notes to action records",
                    "Action records connect a task to responsibility and timing. Meeting notes often leave one of these elements uncertain, so extraction needs a review step.",
                    "Preserve the wording that supports each assignment and flag ambiguity. Do not turn suggestions or hypothetical plans into confirmed tasks without a decision in the notes.",
                    "'We could ask Dana next month' is recorded as a proposal, while 'Dana will send the outline on Friday' becomes an action for review.",
                    "Extract actions from a fictional meeting note containing confirmed tasks and suggestions. Explain why one sentence should not become an assigned task.",
                    "Action lists are reliable when they preserve the difference between proposals and decisions."),
                lesson("Quality checks before sharing",
                    "A final quality check should focus on errors that matter to the document's use. Include source accuracy, completeness, privacy, and clear ownership of approval.",
                    "Use a short checklist suited to the document type. Review the final version after edits, since corrections can introduce new inconsistencies.",
                    "A project update is checked for correct dates, supported claims, unresolved placeholders, and approved distribution before it is shared.",
                    "Write a six-item pre-sharing checklist and apply it to a fictional draft with two intentional errors.",
                    "A consistent final review catches problems that fluent writing can conceal."),
            ),
            module("Final Document Workflow",
                lesson("Defining the final workflow",
                    "The final project should connect a source document to a reviewed deliverable. Choose a realistic but manageable office task with a clear audience.",
                    "Specify the input format, AI operation, validation, and approval step. Keep sensitive real documents outside the practice project.",
                    "A workflow converts fictional meeting notes into a draft recap and action table, then requires a human to verify owners and deadlines.",
                    "Write a workflow brief with one input, two outputs, three accuracy checks, and an approval owner.",
                    "A focused workflow makes the complete document process visible."),
                lesson("Testing the workflow against difficult inputs",
                    "Document workflows should cope with incomplete or inconsistent material. Test these cases before using a polished output as evidence that the process works.",
                    "Include an input with no actions, one with an unclear deadline, and one with conflicting values. The expected result should expose ambiguity rather than resolve it by guessing.",
                    "Notes contain both Tuesday and Thursday for a deadline. The draft flags the conflict and waits for clarification.",
                    "Create three difficult fictional inputs and record the workflow's response. Revise one instruction or review check that failed to expose a problem.",
                    "Difficult inputs reveal whether the workflow preserves uncertainty."),
                lesson("Delivering the document workflow guide",
                    "A handover guide explains how another person can repeat your process. Include accepted inputs, templates, review criteria, and where approved output is stored.",
                    "Show one complete example from source to final document. List the limitations and clarify which decisions remain the reviewer's responsibility.",
                    "A recap guide shows the fictional notes, draft, corrections, and approved version alongside the deadline-checking checklist.",
                    "Package your workflow guide with a complete example and test notes. Ask whether a colleague could run it without an extra explanation.",
                    "A usable handover makes the document workflow repeatable and reviewable."),
            ),
        ],
    },
    {
        "title": "Local LLMs & Private AI",
        "slug": "local-llms-private-ai",
        "level": "advanced",
        "direction": "Private AI",
        "description": (
            "Explore the practical trade-offs of running language models under local control. "
            "This advanced course is for learners familiar with AI workflows who want to evaluate privacy, hardware, and operational constraints. "
            "You will design a small local knowledge workflow with a documented data boundary, model evaluation, and a recovery plan."
        ),
        "modules": [
            module("Local AI Fundamentals",
                lesson("What local inference means",
                    "Local inference means a model generates responses on hardware you control. It changes where computation happens, but it does not automatically settle every privacy question.",
                    "Inspect the complete workflow, including interfaces, logs, document storage, and optional cloud services. A local model connected to a remote component can still send data outside your intended boundary.",
                    "A desktop assistant runs its model locally but uses a separate online search tool. Its data map treats those two operations differently.",
                    "Draw a data path for a fictional local assistant. Label every component and mark which ones could communicate with an external service.",
                    "Privacy depends on the complete system, not just the model's location."),
                lesson("Defining a privacy boundary",
                    "A privacy boundary states which data may enter the workflow and where it may be stored or transmitted. Write it before choosing tools or importing documents.",
                    "Include document copies, prompts, outputs, indexes, and backups. Decide who can access each artifact and how long it should remain available.",
                    "A practice workspace allows fictional documents on one laptop and excludes shared cloud folders, remote model calls, and unnecessary prompt logs.",
                    "Write a boundary statement for a local knowledge project. Include allowed data, allowed storage, access rules, and one excluded connection.",
                    "An explicit boundary gives you something concrete to verify."),
                lesson("Evaluating local and hosted trade-offs",
                    "Local and hosted systems distribute costs and responsibilities differently. Compare them against a defined task rather than assuming one option is universally better.",
                    "Consider quality, speed, hardware cost, maintenance effort, and data requirements. Local control also means responsibility for updates, storage, and reliable operation.",
                    "A small internal summarization task values predictable data handling, while a large multilingual analysis task may require capabilities the available local hardware cannot support.",
                    "Create a comparison table for a fictional task using five criteria. Identify one requirement that could rule out either deployment option.",
                    "Deployment choices should follow task requirements and operational capacity."),
            ),
            module("Models and Hardware",
                lesson("Choosing a model for the task",
                    "A model should be selected by how well it handles your workload, not by its name alone. Build a small evaluation set before downloading several large candidates.",
                    "Check the model's documented intended use, license, language coverage, and compatibility with your runtime. Use representative tasks and include a case where the model should admit uncertainty.",
                    "Two candidates are compared on short English summaries, field extraction, and a question whose answer is absent from the source.",
                    "Write four evaluation cases for a local assistant and list the model information you need before selecting a candidate.",
                    "A task-specific evaluation supports a more informed model choice."),
                lesson("Memory, context, and quantization",
                    "Local inference has practical memory limits. Model weights, runtime overhead, and the active context all contribute to resource use.",
                    "Quantization can reduce the resources needed to store and run weights, with possible quality trade-offs. Longer context can increase memory use, so test your intended workload rather than relying on a model file's size alone.",
                    "A model starts successfully with a short prompt but becomes slow on a long document. The evaluation records both input length and observed memory use.",
                    "Design a resource test with a short and a longer input. Record the metrics you would measure and the quality checks needed when comparing model variants.",
                    "Resource suitability includes both the model and the workload."),
                lesson("Measuring speed and useful quality",
                    "Speed matters only in relation to an acceptable result. Compare latency, completion quality, and review effort under consistent test conditions.",
                    "Record hardware, model variant, input length, and runtime settings. Repeat representative cases and note failed responses rather than reporting only the fastest run.",
                    "A smaller model answers sooner but needs more corrections on extracted deadlines. The comparison includes both response time and the correction count.",
                    "Create a benchmark sheet with five fields and two acceptance criteria. Explain how you would keep two candidate tests comparable.",
                    "A useful benchmark measures the result a person can actually use."),
            ),
            module("Running a Local LLM",
                lesson("Preparing a controlled runtime",
                    "A local runtime loads a model and exposes a way to send requests. Prepare a controlled experiment with trusted software and fictional inputs before adding integrations.",
                    "Read the runtime's current documentation for supported hardware, model formats, and configuration. Verify download sources and record versions so the setup can be reproduced.",
                    "A setup note records the operating system, runtime version, model identifier, and one short test request using invented information.",
                    "Write a setup checklist and a reproducibility record. Include one item you must verify in current documentation rather than assume from an old tutorial.",
                    "A recorded setup makes later troubleshooting and comparison easier."),
                lesson("Verifying local access and connections",
                    "A model server may expose an interface to other programs or devices. Check its listening address and access controls before treating it as a private local service.",
                    "Keep a practice service limited to the intended machine and inspect optional remote features. Review the client as well as the server because either may introduce an external connection.",
                    "A local knowledge prototype documents its runtime address and confirms that its interface does not call a hosted model when the local model is unavailable.",
                    "Create a connection checklist covering the model server, interface, and optional tools. Describe how you would detect an unexpected remote fallback.",
                    "A verified connection path is part of a private deployment."),
                lesson("Testing prompts and failure behavior",
                    "A running model still needs behavioral tests. Check whether it follows the task, uses supplied evidence, and handles an incomplete input without inventing facts.",
                    "Also test an unavailable runtime and an oversized input. The surrounding workflow should report the problem clearly instead of silently changing models or presenting an empty result as success.",
                    "A summarization client shows an explicit connection error when the local service stops and leaves the original document available for retry.",
                    "Plan tests for a supported task, missing evidence, and runtime failure. Define the user-visible result for each case.",
                    "Operational failures deserve tests alongside generated answers."),
            ),
            module("Private Knowledge Workflows",
                lesson("Preparing a local document collection",
                    "A local knowledge workflow starts with a deliberately selected document collection. Keep original sources and derived artifacts organized within the chosen privacy boundary.",
                    "Record document identifiers, versions, permissions, and removal rules. Derived notes and indexes may contain sensitive information even when they do not resemble the original files.",
                    "A practice collection contains three fictional project notes, each with an identifier and version. The workspace records which summaries depend on each note.",
                    "Design a document manifest for three fictional files. Include where originals and derived artifacts live and how an outdated version is marked.",
                    "Local document control includes the artifacts created from those documents."),
                lesson("Retrieving evidence before generation",
                    "Retrieval selects relevant source material before a model answers a question. It can improve access to a document collection, but it does not guarantee that the answer is supported.",
                    "Inspect the retrieved passages and retain their source identifiers. Ask the model to answer only from those passages and require review when the necessary evidence is absent.",
                    "A project question retrieves a schedule note. A question about an unrecorded budget returns no supported answer instead of a plausible estimate.",
                    "Choose two questions for your fictional collection. Identify the passages needed for one and explain why the other should remain unanswered.",
                    "Retrieval is useful when the evidence remains visible beside the answer."),
                lesson("Reviewing answers, logs, and retention",
                    "A private knowledge workflow needs checks for both answer quality and stored data. A correct answer does not prove that the system's logs or backups respect the boundary.",
                    "Review factual support and inspect which artifacts each run creates. Define retention for prompts, generated text, indexes, and any exported results.",
                    "A prototype stores source identifiers and execution status, while avoiding unnecessary copies of full document text in routine logs.",
                    "Write a combined review checklist with three answer checks and three data-handling checks. Include a plan for removing a document and its derived artifacts.",
                    "Quality review and data handling are separate responsibilities that both need evidence."),
            ),
            module("Final Local AI Project",
                lesson("Specifying a local knowledge assistant",
                    "The final project should demonstrate one useful task inside a documented local boundary. Choose a small collection and limit the assistant's responsibilities.",
                    "Define the runtime, accepted documents, answer format, and unsupported-question behavior. Keep the practice project free of real confidential material.",
                    "A fictional project assistant answers schedule questions from three local notes, includes source identifiers, and flags questions outside the collection.",
                    "Write a project specification with a data map, three acceptance criteria, and one explicitly unsupported task.",
                    "A bounded specification makes local-control claims testable."),
                lesson("Evaluating the complete local workflow",
                    "Evaluate the project from document input to reviewed answer. Include retrieval quality, source support, response time, and behavior when components fail.",
                    "Use a fixed set of supported and unsupported questions. Check the data path and stored artifacts as well as the visible response.",
                    "A test records whether the right source was retrieved, whether the answer used it correctly, and what the client displayed after the runtime was stopped.",
                    "Prepare four end-to-end test cases and an evidence log. Record one limitation in quality or performance that remains after testing.",
                    "End-to-end evaluation tests the workflow you will actually operate."),
                lesson("Documenting maintenance and recovery",
                    "A local deployment needs a plan for updates, backups, and failure recovery. Its operating guide should make these responsibilities clear to a future maintainer.",
                    "Record the tested setup and retest important cases after changes. Explain how to restore approved documents, rebuild derived artifacts, and stop the service when a problem occurs.",
                    "A handover contains the model and runtime versions, collection manifest, privacy boundary, test results, and steps for rebuilding the workspace from approved sources.",
                    "Prepare a short operating guide with a recovery sequence and an update checklist. State which tests must pass before normal use resumes.",
                    "Local control is sustainable when maintenance and recovery are documented."),
            ),
        ],
    },
]
