# Generated by Django 6.1 on 2026-10-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_mode',
            field=models.CharField(choices=[('approval', 'Approval required'), ('open', 'Open enrollment')], default='approval', max_length=20),
        ),
    ]
